import Icon from './Icon'

const features = [
  ['RAG-Grounded Answers', 'Relevant information is retrieved from the knowledge base before the AI generates its response.', 'RAG Powered', 'Question  →  Retrieve Knowledge  →  Grounded Answer', 'indigo'],
  ['Source Evidence', 'See the source document, relevant section, and short supporting evidence with relevant answers.', 'Traceable', 'Account Help Guide.pdf  ·  § Password Reset', 'violet'],
  ['Local AI & Privacy', 'Responses use locally controlled organization knowledge for a more private support experience.', 'Private', 'Knowledge Base  →  Local RAG  →  Answer', 'cyan'],
  ['Voice & Multilingual Support', 'Ask questions using voice input and supported languages for accessible assistance.', 'English · हिंदी · मराठी', 'Listening...  →  Transcribing...  →  Ready', 'violet'],
  ['Conversation History & Feedback', 'Revisit previous support conversations and provide simple feedback on AI responses.', 'Rated', 'Password Reset  ·  Account Settings', 'indigo'],
  ['Knowledge Base Improvement', 'Repeated unanswered questions become visible knowledge gaps for candidate FAQ content.', 'Continuous Learning', 'Unanswered Q  →  Recurring Gap  →  AI FAQ Draft', 'amber'],
  ['Admin-Controlled Knowledge', 'FAQ drafts are reviewed and approved before becoming searchable knowledge.', 'Human Review', 'FAQ Draft  →  Admin Review  →  Re-indexed Knowledge', 'indigo'],
]

export default function FeatureShowcase() {
  return <section className="relative border-t border-indigo-100/70 bg-gradient-to-b from-white/40 via-indigo-50/20 to-transparent py-20" id="features"><div className="mx-auto max-w-6xl px-6"><div className="mx-auto mb-14 max-w-2xl text-center"><span className="mb-3 inline-flex rounded-full border border-indigo-100 bg-indigo-50 px-3 py-1 text-[11px] font-bold uppercase tracking-wider text-indigo-700">Feature Showcase</span><h2 className="text-2xl font-extrabold tracking-tight text-slate-900 sm:text-3xl md:text-4xl">Everything you need for <span className="hero-gradient">reliable AI support</span></h2><p className="mt-3 text-[15px] leading-relaxed text-slate-600">Built around grounded answers, controlled knowledge, privacy, and a better customer experience.</p></div><div className="mb-8 rounded-2xl bg-gradient-to-r from-indigo-900 via-indigo-800 to-violet-900 p-6 text-white shadow-xl shadow-indigo-900/10"><div className="flex flex-col items-start justify-between gap-6 md:flex-row md:items-center"><div className="flex items-start gap-4"><div className="flex h-12 w-12 flex-shrink-0 items-center justify-center rounded-xl border border-white/20 bg-white/10 text-cyan-300"><Icon name="chat" size={26} /></div><div><div className="mb-1 flex items-center gap-2 text-xs font-bold uppercase tracking-widest text-cyan-300">Foundation <span className="h-1 w-1 rounded-full bg-cyan-300" /> <span className="font-medium text-indigo-200">Conversational Interface</span></div><h3 className="text-lg font-bold tracking-tight sm:text-xl">AI Customer Support</h3><p className="mt-1 max-w-2xl text-sm leading-relaxed text-indigo-100/90">Ask organization-specific support questions naturally through an intelligent conversational interface designed for clarity and trust.</p></div></div><span className="rounded-xl border border-white/15 bg-white/10 px-3.5 py-2 text-xs font-medium text-cyan-200"><span className="mr-2 inline-block h-2 w-2 rounded-full bg-cyan-400" />Interactive Support Agent</span></div></div><div className="grid grid-cols-1 gap-6 md:grid-cols-2">{features.slice(0, 2).map((feature) => <FeatureCard feature={feature} key={feature[0]} />)}</div><div className="mt-6 grid grid-cols-1 gap-6 md:grid-cols-3">{features.slice(2, 5).map((feature) => <FeatureCard feature={feature} key={feature[0]} />)}</div><div className="mt-6 grid grid-cols-1 gap-6 md:grid-cols-2">{features.slice(5).map((feature) => <FeatureCard feature={feature} key={feature[0]} />)}</div></div></section>
}

function FeatureCard({ feature }) { const [title, description, tag, preview, tone] = feature; const colors = { indigo: 'bg-indigo-50 text-indigo-600', violet: 'bg-violet-50 text-violet-600', cyan: 'bg-cyan-50 text-cyan-600', amber: 'bg-amber-50 text-amber-600' }; return <article className="flex flex-col justify-between rounded-2xl border border-indigo-100/90 bg-white/90 p-6 shadow-sm backdrop-blur-xl transition hover:-translate-y-0.5 hover:border-indigo-300 hover:shadow-md"><div><div className="mb-4 flex items-center justify-between"><div className={`flex h-10 w-10 items-center justify-center rounded-xl ${colors[tone]}`}><Icon name={tone === 'cyan' ? 'shield' : tone === 'amber' ? 'spark' : 'doc'} size={22} /></div><span className={`rounded-full border border-indigo-200 px-2.5 py-1 text-[11px] font-bold tracking-wide ${colors[tone]}`}>{tag}</span></div><h3 className="mb-2 text-base font-bold text-slate-900 sm:text-lg">{title}</h3><p className="mb-6 text-[13.5px] leading-relaxed text-slate-600">{description}</p></div><div className="rounded-xl border border-indigo-50 bg-slate-50/80 p-3 text-[11px] font-medium text-slate-600">{preview}</div></article> }