import Icon from './Icon'

const stepsByLanguage = {
  en: [['ASK', 'Type or speak your question in natural language.', 'chat', 'indigo'], ['FIND', 'Relevant verified information is retrieved from the knowledge base.', 'search', 'violet'], ['ANSWER', 'Receive a clear answer accompanied by supporting source references.', 'spark', 'cyan']],
  hi: [['पूछें', 'प्राकृतिक भाषा में अपना सवाल टाइप या बोलें।', 'chat', 'indigo'], ['खोजें', 'सत्यापित प्रासंगिक जानकारी नॉलेज बेस से ली जाती है।', 'search', 'violet'], ['उत्तर पाएँ', 'सहायक स्रोत संदर्भों के साथ स्पष्ट उत्तर प्राप्त करें।', 'spark', 'cyan']],
  mr: [['प्रश्न करा', 'प्राकृतिक भाषेत तुमचा प्रश्न टाइप किंवा बोला.', 'chat', 'indigo'], ['शोधा', 'सत्यापित प्रासंगिक माहिती नॉलेज बेसमधून घेतली जाते.', 'search', 'violet'], ['उत्तर मिळवा', 'सहायक स्त्रोत संदर्भांसह स्पष्ट उत्तर मिळवा.', 'spark', 'cyan']],
}

export default function HowItWorks({ language = 'en' }) {
  const steps = stepsByLanguage[language] || stepsByLanguage.en
  return <section className="border-t border-indigo-100/60 py-16" id="how-it-works"><div className="mx-auto max-w-4xl px-6"><div className="mb-12 text-center"><span className="rounded-full bg-indigo-50 px-3 py-1 text-[11px] font-bold uppercase tracking-wider text-indigo-700">{language === 'en' ? 'Seamless Workflow' : language === 'hi' ? 'सुसंगत कार्यप्रवाह' : 'सुसंगत कार्यप्रवाह'}</span><h2 className="mt-3 text-2xl font-bold tracking-tight text-slate-900">{language === 'en' ? 'Simple support, grounded answers.' : language === 'hi' ? 'सरल सहायता, सत्यापित उत्तर।' : 'सोपे समर्थन, आधारभूत उत्तरे.'}</h2></div><div className="grid grid-cols-1 gap-8 md:grid-cols-3">{steps.map(([title, text, icon, tone], index) => <div className="group flex flex-col items-center text-center" key={title}><div className="relative mb-4 flex h-14 w-14 items-center justify-center rounded-2xl border border-indigo-100 bg-white shadow-lg shadow-indigo-500/5 transition group-hover:scale-110 group-hover:border-indigo-400"><div className={`flex h-10 w-10 items-center justify-center rounded-xl ${tone === 'indigo' ? 'bg-indigo-50 text-indigo-600' : tone === 'violet' ? 'bg-violet-50 text-violet-600' : 'bg-cyan-50 text-cyan-600'}`}><Icon name={icon} size={20} /></div><span className="absolute -right-2 -top-2 rounded-full bg-gradient-to-r from-indigo-600 to-violet-600 px-1.5 py-0.5 font-mono text-[10px] font-bold text-white">0{index + 1}</span></div><h3 className="mb-1.5 text-[15px] font-bold tracking-tight text-slate-900">{title}</h3><p className="max-w-xs text-[13px] leading-relaxed text-slate-500">{text}</p></div>)}</div></div></section> }